MusicDatabaseFinal/Models/ErrorViewModel.cs
namespace MusicDatabaseFinal.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MusicDatabaseFinal/Models/IMusicRepository.cs
using System;
namespace MusicDatabaseFinal.Models
{
	public interface IMusicRepository
	{
		public IEnumerable<Music> GetAllMusic();
		public Music GetMusic(int id);
		public void UpdateMusic(Music music);
        public void InsertMusic(Music musicToInsert);
        public IEnumerable<Music> GetMusic();
        public Music AssignMusic();
		public void DeleteMusic(Music music);
    }
}

MusicDatabaseFinal/Models/Music.cs
using System;
namespace MusicDatabaseFinal.Models
{
	public class Music
	{
		public Music()
		{
		}
        public int ID { get; set; }

        public string ArtistName { get; set; }

        public string AlbumName { get; set; }

        public int YearReleased { get; set; }

        public string Genre { get; set; }

        public double MyRating { get; set; }

        public IEnumerable<Music> Musics { get; set; }
    }
}

MusicDatabaseFinal/Models/MusicRepository.cs
using System;
using System.Data;
using Dapper;

namespace MusicDatabaseFinal.Models
{
	public class MusicRepository : IMusicRepository
	{
        private readonly IDbConnection _conn;

		public MusicRepository(IDbConnection conn)
		{
            _conn = conn;
		}

        public Music AssignMusic()
        {
            var musicList = GetMusic();
            var music = new Music();
            music.Musics = musicList;
            return music;
        }

        public IEnumerable<Music> GetAllMusic()
        {
            return _conn.Query<Music>("SELECT * FROM MUSIC;");
        }

        public Music GetMusic(int id)
        {
            return _conn.QuerySingle<Music>("SELECT * FROM MUSIC WHERE ID = @id", new { id = id });
        }

        public IEnumerable<Music> GetMusic()
        {
            return _conn.Query<Music>("SELECT * FROM music;");
        }

        public void InsertMusic(Music musicToInsert)
        {
            _conn.Execute("INSERT INTO music (ArtistName, AlbumName, YearReleased, Genre, MyRating) VALUES (@artistName, @albumName, @yearReleased, @genre, @myRating);",
                new {artistName = musicToInsert.ArtistName, albumName = musicToInsert.AlbumName, yearReleased = musicToInsert.YearReleased, genre = musicToInsert.Genre, myRating = musicToInsert.MyRating });
        }

        public void UpdateMusic(Music music)
        {
            _conn.Execute("UPDATE MUSIC SET ArtistName = @artistName, AlbumName = @albumName, YearReleased = @yearReleased, Genre = @genre, MyRating = @myRating WHERE ID = @id",
                    new { artistName = music.ArtistName, albumName = music.AlbumName, yearReleased = music.YearReleased, genre = music.Genre, myRating = music.MyRating, id = music.ID });
        }

        public void DeleteMusic(Music music)
        {
            _conn.Execute("DELETE FROM MUSIC WHERE ID = @id;", new { id = music.ID });
        }
    }
}

MusicDatabaseFinal/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MusicDatabaseFinal.Models;

namespace MusicDatabaseFinal.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MusicDatabaseFinal/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MusicDatabaseFinal.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MusicDatabaseFinal.Controllers
{
    public class MusicController : Controller
    {
        private readonly IMusicRepository repo;

        public MusicController(IMusicRepository repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            var music = repo.GetAllMusic();
            return View(music);
        }

        public IActionResult ViewMusic(int id)
        {
            var product = repo.GetMusic(id);
            return View(product);
        }

        public IActionResult UpdateMusic(int id)
        {
            Music music = repo.GetMusic(id);
            if (music == null)
            {
                return View("MusicNotFound");
            }
            return View(music);
        }

        public IActionResult UpdateMusicToDatabase(Music music)
        {
            repo.UpdateMusic(music);

            return RedirectToAction("ViewMusic", new { id = music.ID });
        }

        public IActionResult InsertMusic()
        {
            var music = repo.AssignMusic();
            return View(music);
        }

        public IActionResult InsertMusicToDatabase(Music musicToInsert)
        {
            repo.InsertMusic(musicToInsert);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteMusic(Music music)
        {
            repo.DeleteMusic(music);
            return RedirectToAction("Index");
        }
    }
}

MusicDatabaseFinal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}





    <div class="text-center">
        <h1 class="display-4">MyMusicDatabase</h1>
        <p>Hello! This is a page to help me store and track different albums I've listened to,</p>
        <p></p>
        <p></p>
        <p><a href="https://localhost:7248/Music" style="text-shadow:1px 1px 0 #444">Check It Out Here!</a></p>
        <img src="/../Stop-Making-Sense-image.jpeg">
    </div>

MusicDatabaseFinal/Views/Music/Index.cshtml
@model IEnumerable<Music>


<h2>Music</h2>

<div style="display: block">
    <a href="/Music/InsertMusic/" class="center" style="text-shadow:1px 1px 0 #444">Add a new entry!</a>
</div>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Artist Name</th>
        <th>Album Name</th>
        <th>Year Released</th>
        <th>Genre</th>
        <th>My Rating</th>
    </tr>

    @foreach (var music in @Model)
    {
        <tr>
            <td><a href=/Music/ViewMusic/@music.ID>@music.ID</a></td>
            <td>@music.ArtistName</td>
            <td>@music.AlbumName</td>
            <td>@music.YearReleased</td>
            <td>@music.Genre</td>
            <td>@music.MyRating</td>
        </tr>
    }

</table>

MusicDatabaseFinal/Views/Music/InsertMusic.cshtml
@model Music

<h2>Add a new entry</h2>

@using (Html.BeginForm("InsertMusicToDataBase", "Music", "Post"))
{
    <input asp-for="ID" type="hidden" value="" />

    <label asp-for="ArtistName" class="control-label">ArtistName</label>
    <input type="text" name="ArtistName" class="form-control" value="" />

    <label asp-for="AlbumName" class="control-label">AlbumName</label>
    <input type="text" name="AlbumName" class="form-control" value="" />

    <label asp-for="YearReleased" class="control-label">Year Released</label>
    <input type="number" name="YearReleased" class="form-control" />

    <label asp-for="Genre" class="control-label">Genre</label>
    <input type="text" name="Genre" class="form-control" value="" />

    <label asp-for="MyRating" class="control-label">MyRating</label>
    <input type="number" name="MyRating" class="form-control" />

  

    <input type="submit" value="Create Music" class="btn btn-primary" />
}

MusicDatabaseFinal/Views/Music/UpdateMusic.cshtml
@model Music

<h2>Update @Model.ArtistName</h2>

@using (Html.BeginForm("UpdateMusicToDatabase", "Music", "Post"))
{
    <input asp-for="ID" type="hidden" value="@Model.ID" />

    <label asp-for="ArtistName" class="control-label">ArtistName</label>
    <input type="text" name="ArtistName" class="form-control" value="@Model.ArtistName" />

    <label asp-for="AlbumName" class="control-label">AlbumName</label>
    <input type="text" name="AlbumName" class="form-control" value="@Model.AlbumName" />

    <label asp-for="YearReleased" class="control-label">YearReleased</label>
    <input type="number" name="YearReleased" class="form-control" value="@Model.YearReleased" />

    <label asp-for="Genre" class="control-label">Genre</label>
    <input type="text" name="Genre" class="form-control" value="@Model.Genre" />

    <label asp-for="MyRating" class="control-label">MyRating</label>
    <input type="number" name="MyRating" class="form-control" value="@Model.MyRating" />

    <input type="submit" value="Update Music" class="btn btn-primary" />
}

MusicDatabaseFinal/Views/Music/ViewMusic.cshtml
@model Music

<h3>@Model.ID Information</h3>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Artist Name</th>
        <th>Album Name</th>
        <th>Year Released</th>
        <th>Genre</th>
        <th>My Rating</th>
    </tr>
    <tr>
        <td>@Model.ID</td>
        <td>@Model.ArtistName</td>
        <td>@Model.AlbumName</td>
        <td>@Model.YearReleased</td>
        <td>@Model.Genre</td>
        <td>@Model.MyRating</td>
    </tr>
</table>

<div style="display: block">
    <a href="/Music/UpdateMusic/@Model.ID" style="text-shadow:1px 1px 0 #444">Edit this entry</a>
</div>
<div>
    <a></a>
</div>
<div>
    <a>OR!!</a>
</div>
<div>
    <a></a>
</div>
<div style="display: block">

    @using (Html.BeginForm("DeleteMusic", "Music", "Post"))
    {
        <input type="hidden" asp-for="ID" value="@Model.ID" />
        <input type="submit" onclick="return confirm('Are you sure?')" style="text-shadow:1px 1px 0 #444" value="Delete this entry" />
    }
</div>

MusicDatabaseFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicDatabaseFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MusicDatabaseFinal.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MusicDatabaseFinal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Music" asp-action="Index">Music</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MusicDatabaseFinal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>